global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: muffin-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
        - muffin-wallet-monitoring.ru:8080